export const GET_TODO_LIST_ASYNC = 'GET_TODO_LIST_ASYNC';
export const DELETE_TODO_LIST_ITEM_ASYNC = 'DELETE_TODO_LIST_ITEM_ASYNC';
export const ADD_TODO_LIST_ITEM_ASYNC = 'ADD_TODO_LIST_ITEM_ASYNC';
